# defaults are setup for the platform engineering slack workspace
slack:
  #bot_token: no default
  #app_token: no default
  report_channel: bot-test
  report_channel_id: C01KHKNJUKE

jira:
  start_transition_id: 21
  done_transition_id: 41
  project: SBOX
  issue_type_name: Bug
  issue_type_id: 10900
  #username: no default
  #api_token: no default

app_insights:
  #instrumentation_key: no default
  role_name: ccpay-slack-help-bot
